### ISSUE TITLE
Latest Changes from Google

### ISSUE THREAD

**Issue by ellemayo** [klinker24/launcher3#5]
Any intention to update this source code to include the latest changes from Google? 

Looks like it has been a year since it was updated - curious if this is still an active project or if there is something else more updated that has forked off from this.

Thanks

**Comment by klinker24** [comment]
I will work on this fork whenever I have time. My other apps, that are paid, take priority over this one, sorry. Blur has been at a standstill for awhile, so this fork hasn't been updated either.

Feel free to pull in Google's changes and submit a PR. The instructions are in the readme. I'm sure there will be conflicts that would need to be resolved though, there always are.

**Comment by ellemayo** [comment]
Thanks for the quick response! 

I'll look into what the merge would require.
